/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRunsRouteImport } from './routes/_authenticated/runs'
import { Route as AuthenticatedPresetsRouteImport } from './routes/_authenticated/presets'
import { Route as AuthenticatedNewRunRouteImport } from './routes/_authenticated/new-run'
import { Route as AuthenticatedHealthRouteImport } from './routes/_authenticated/health'
import { Route as AuthenticatedCompareRouteImport } from './routes/_authenticated/compare'
import { Route as AuthenticatedBatchesRouteImport } from './routes/_authenticated/batches'
import { Route as AuthenticatedRunsIndexRouteImport } from './routes/_authenticated/runs.index'
import { Route as AuthenticatedBatchesIndexRouteImport } from './routes/_authenticated/batches.index'
import { Route as AuthenticatedRunsRunIdRouteImport } from './routes/_authenticated/runs.$runId'
import { Route as AuthenticatedBatchesNewRouteImport } from './routes/_authenticated/batches.new'
import { Route as AuthenticatedBatchesBatchIdRouteImport } from './routes/_authenticated/batches.$batchId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRunsRoute = AuthenticatedRunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPresetsRoute = AuthenticatedPresetsRouteImport.update({
  id: '/presets',
  path: '/presets',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNewRunRoute = AuthenticatedNewRunRouteImport.update({
  id: '/new-run',
  path: '/new-run',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHealthRoute = AuthenticatedHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCompareRoute = AuthenticatedCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBatchesRoute = AuthenticatedBatchesRouteImport.update({
  id: '/batches',
  path: '/batches',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRunsIndexRoute = AuthenticatedRunsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRunsRoute,
} as any)
const AuthenticatedBatchesIndexRoute =
  AuthenticatedBatchesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedBatchesRoute,
  } as any)
const AuthenticatedRunsRunIdRoute = AuthenticatedRunsRunIdRouteImport.update({
  id: '/$runId',
  path: '/$runId',
  getParentRoute: () => AuthenticatedRunsRoute,
} as any)
const AuthenticatedBatchesNewRoute = AuthenticatedBatchesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedBatchesRoute,
} as any)
const AuthenticatedBatchesBatchIdRoute =
  AuthenticatedBatchesBatchIdRouteImport.update({
    id: '/$batchId',
    path: '/$batchId',
    getParentRoute: () => AuthenticatedBatchesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/batches': typeof AuthenticatedBatchesRouteWithChildren
  '/compare': typeof AuthenticatedCompareRoute
  '/health': typeof AuthenticatedHealthRoute
  '/new-run': typeof AuthenticatedNewRunRoute
  '/presets': typeof AuthenticatedPresetsRoute
  '/runs': typeof AuthenticatedRunsRouteWithChildren
  '/batches/$batchId': typeof AuthenticatedBatchesBatchIdRoute
  '/batches/new': typeof AuthenticatedBatchesNewRoute
  '/runs/$runId': typeof AuthenticatedRunsRunIdRoute
  '/batches/': typeof AuthenticatedBatchesIndexRoute
  '/runs/': typeof AuthenticatedRunsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/compare': typeof AuthenticatedCompareRoute
  '/health': typeof AuthenticatedHealthRoute
  '/new-run': typeof AuthenticatedNewRunRoute
  '/presets': typeof AuthenticatedPresetsRoute
  '/batches/$batchId': typeof AuthenticatedBatchesBatchIdRoute
  '/batches/new': typeof AuthenticatedBatchesNewRoute
  '/runs/$runId': typeof AuthenticatedRunsRunIdRoute
  '/batches': typeof AuthenticatedBatchesIndexRoute
  '/runs': typeof AuthenticatedRunsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/batches': typeof AuthenticatedBatchesRouteWithChildren
  '/_authenticated/compare': typeof AuthenticatedCompareRoute
  '/_authenticated/health': typeof AuthenticatedHealthRoute
  '/_authenticated/new-run': typeof AuthenticatedNewRunRoute
  '/_authenticated/presets': typeof AuthenticatedPresetsRoute
  '/_authenticated/runs': typeof AuthenticatedRunsRouteWithChildren
  '/_authenticated/batches/$batchId': typeof AuthenticatedBatchesBatchIdRoute
  '/_authenticated/batches/new': typeof AuthenticatedBatchesNewRoute
  '/_authenticated/runs/$runId': typeof AuthenticatedRunsRunIdRoute
  '/_authenticated/batches/': typeof AuthenticatedBatchesIndexRoute
  '/_authenticated/runs/': typeof AuthenticatedRunsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/batches'
    | '/compare'
    | '/health'
    | '/new-run'
    | '/presets'
    | '/runs'
    | '/batches/$batchId'
    | '/batches/new'
    | '/runs/$runId'
    | '/batches/'
    | '/runs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/compare'
    | '/health'
    | '/new-run'
    | '/presets'
    | '/batches/$batchId'
    | '/batches/new'
    | '/runs/$runId'
    | '/batches'
    | '/runs'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/batches'
    | '/_authenticated/compare'
    | '/_authenticated/health'
    | '/_authenticated/new-run'
    | '/_authenticated/presets'
    | '/_authenticated/runs'
    | '/_authenticated/batches/$batchId'
    | '/_authenticated/batches/new'
    | '/_authenticated/runs/$runId'
    | '/_authenticated/batches/'
    | '/_authenticated/runs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/runs': {
      id: '/_authenticated/runs'
      path: '/runs'
      fullPath: '/runs'
      preLoaderRoute: typeof AuthenticatedRunsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/presets': {
      id: '/_authenticated/presets'
      path: '/presets'
      fullPath: '/presets'
      preLoaderRoute: typeof AuthenticatedPresetsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/new-run': {
      id: '/_authenticated/new-run'
      path: '/new-run'
      fullPath: '/new-run'
      preLoaderRoute: typeof AuthenticatedNewRunRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/health': {
      id: '/_authenticated/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof AuthenticatedHealthRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/compare': {
      id: '/_authenticated/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof AuthenticatedCompareRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/batches': {
      id: '/_authenticated/batches'
      path: '/batches'
      fullPath: '/batches'
      preLoaderRoute: typeof AuthenticatedBatchesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/runs/': {
      id: '/_authenticated/runs/'
      path: '/'
      fullPath: '/runs/'
      preLoaderRoute: typeof AuthenticatedRunsIndexRouteImport
      parentRoute: typeof AuthenticatedRunsRoute
    }
    '/_authenticated/batches/': {
      id: '/_authenticated/batches/'
      path: '/'
      fullPath: '/batches/'
      preLoaderRoute: typeof AuthenticatedBatchesIndexRouteImport
      parentRoute: typeof AuthenticatedBatchesRoute
    }
    '/_authenticated/runs/$runId': {
      id: '/_authenticated/runs/$runId'
      path: '/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof AuthenticatedRunsRunIdRouteImport
      parentRoute: typeof AuthenticatedRunsRoute
    }
    '/_authenticated/batches/new': {
      id: '/_authenticated/batches/new'
      path: '/new'
      fullPath: '/batches/new'
      preLoaderRoute: typeof AuthenticatedBatchesNewRouteImport
      parentRoute: typeof AuthenticatedBatchesRoute
    }
    '/_authenticated/batches/$batchId': {
      id: '/_authenticated/batches/$batchId'
      path: '/$batchId'
      fullPath: '/batches/$batchId'
      preLoaderRoute: typeof AuthenticatedBatchesBatchIdRouteImport
      parentRoute: typeof AuthenticatedBatchesRoute
    }
  }
}

interface AuthenticatedBatchesRouteChildren {
  AuthenticatedBatchesBatchIdRoute: typeof AuthenticatedBatchesBatchIdRoute
  AuthenticatedBatchesNewRoute: typeof AuthenticatedBatchesNewRoute
  AuthenticatedBatchesIndexRoute: typeof AuthenticatedBatchesIndexRoute
}

const AuthenticatedBatchesRouteChildren: AuthenticatedBatchesRouteChildren = {
  AuthenticatedBatchesBatchIdRoute: AuthenticatedBatchesBatchIdRoute,
  AuthenticatedBatchesNewRoute: AuthenticatedBatchesNewRoute,
  AuthenticatedBatchesIndexRoute: AuthenticatedBatchesIndexRoute,
}

const AuthenticatedBatchesRouteWithChildren =
  AuthenticatedBatchesRoute._addFileChildren(AuthenticatedBatchesRouteChildren)

interface AuthenticatedRunsRouteChildren {
  AuthenticatedRunsRunIdRoute: typeof AuthenticatedRunsRunIdRoute
  AuthenticatedRunsIndexRoute: typeof AuthenticatedRunsIndexRoute
}

const AuthenticatedRunsRouteChildren: AuthenticatedRunsRouteChildren = {
  AuthenticatedRunsRunIdRoute: AuthenticatedRunsRunIdRoute,
  AuthenticatedRunsIndexRoute: AuthenticatedRunsIndexRoute,
}

const AuthenticatedRunsRouteWithChildren =
  AuthenticatedRunsRoute._addFileChildren(AuthenticatedRunsRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedBatchesRoute: typeof AuthenticatedBatchesRouteWithChildren
  AuthenticatedCompareRoute: typeof AuthenticatedCompareRoute
  AuthenticatedHealthRoute: typeof AuthenticatedHealthRoute
  AuthenticatedNewRunRoute: typeof AuthenticatedNewRunRoute
  AuthenticatedPresetsRoute: typeof AuthenticatedPresetsRoute
  AuthenticatedRunsRoute: typeof AuthenticatedRunsRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBatchesRoute: AuthenticatedBatchesRouteWithChildren,
  AuthenticatedCompareRoute: AuthenticatedCompareRoute,
  AuthenticatedHealthRoute: AuthenticatedHealthRoute,
  AuthenticatedNewRunRoute: AuthenticatedNewRunRoute,
  AuthenticatedPresetsRoute: AuthenticatedPresetsRoute,
  AuthenticatedRunsRoute: AuthenticatedRunsRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
